# _plugins/runner_game_pages.rb
#
# Jekyll Generator Plugin
# Automatically creates /runners/{runner_id}/runs/{game_id}/ pages
# based on runs in the _runs collection.
#
# This eliminates the need to manually create these pages.

module Jekyll
  class RunnerGamePage < Page
    def initialize(site, base, runner_id, game_id, runner_name, game_name)
      @site = site
      @base = base
      @dir = "runners/#{runner_id}/runs/#{game_id}"
      @name = "index.html"

      self.process(@name)
      self.read_yaml(File.join(base, '_layouts'), 'runner-game-runs.html')
      
      # Set page data
      self.data['layout'] = 'runner-game-runs'
      self.data['title'] = "#{runner_name} - #{game_name} Runs"
      self.data['runner_id'] = runner_id
      self.data['game_id'] = game_id
      self.data['permalink'] = "/runners/#{runner_id}/runs/#{game_id}/"
      self.data['autogenerated'] = true
    end
  end

  class RunnerGamePageGenerator < Generator
    safe true
    priority :low

    def generate(site)
      # Skip if no runs collection
      return unless site.collections.key?('runs')
      
      runs = site.collections['runs'].docs
      runners = site.collections['runners']&.docs || []
      games = site.collections['games']&.docs || []
      
      # Build lookup hashes for runner and game names
      runner_names = {}
      runners.each do |r|
        rid = r.data['runner_id']
        runner_names[rid] = r.data['runner_name'] || rid if rid
      end
      
      game_names = {}
      games.each do |g|
        gid = g.data['game_id']
        game_names[gid] = g.data['game_name'] || gid if gid
      end
      
      # Find unique runner+game combinations from runs
      runner_game_pairs = Set.new
      
      runs.each do |run|
        runner_id = run.data['runner_id']
        game_id = run.data['game_id']
        
        next unless runner_id && game_id
        next if runner_id.to_s.strip.empty? || game_id.to_s.strip.empty?
        
        # Normalize IDs
        runner_id = runner_id.to_s.strip.downcase
        game_id = game_id.to_s.strip.downcase
        
        runner_game_pairs.add([runner_id, game_id])
      end
      
      # Check for existing pages to avoid duplicates
      existing_pages = Set.new
      site.pages.each do |page|
        if page.data['runner_id'] && page.data['game_id']
          existing_pages.add([page.data['runner_id'], page.data['game_id']])
        end
      end
      
      # Also check for manually created pages in the filesystem
      Dir.glob(File.join(site.source, 'runners', '*', 'runs', '*', 'index.html')).each do |path|
        # Extract runner_id and game_id from path
        match = path.match(/runners\/([^\/]+)\/runs\/([^\/]+)\/index\.html$/)
        if match
          existing_pages.add([match[1], match[2]])
        end
      end
      
      # Generate pages for each unique combination
      generated_count = 0
      
      runner_game_pairs.each do |runner_id, game_id|
        # Skip if page already exists
        next if existing_pages.include?([runner_id, game_id])
        
        runner_name = runner_names[runner_id] || runner_id.split('-').map(&:capitalize).join(' ')
        game_name = game_names[game_id] || game_id.split('-').map(&:capitalize).join(' ')
        
        page = RunnerGamePage.new(site, site.source, runner_id, game_id, runner_name, game_name)
        site.pages << page
        generated_count += 1
      end
      
      if generated_count > 0
        Jekyll.logger.info "RunnerGamePages:", "Generated #{generated_count} runner game page(s)"
      end
    end
  end
end
