name: "🔧 Game Change Request"
description: "Request a change or update to an existing game's information"
title: "[Game Change] "
labels: ["game-change", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Game Change Request
        Use this form to request updates to an existing game's categories, challenges, rules, or other information.
        
        A moderator will review your request and make the appropriate changes.

  - type: input
    id: game_name
    attributes:
      label: "Game Name"
      description: "Which game needs to be updated?"
      placeholder: "e.g., Hades II"
    validations:
      required: true

  - type: dropdown
    id: change_type
    attributes:
      label: "Type of Change"
      description: "What kind of change are you requesting?"
      options:
        - "Add new category"
        - "Modify existing category"
        - "Remove category"
        - "Add new challenge type"
        - "Update glitch rules"
        - "Add/update version or DLC tracking"
        - "Fix incorrect information"
        - "Update timing method"
        - "Add community challenge"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: current_state
    attributes:
      label: "Current State"
      description: "What is the current information that needs to be changed? (if applicable)"
      placeholder: |
        Example: 
        - Current category: "Any%" 
        - Current definition: Reach the credits

  - type: textarea
    id: requested_change
    attributes:
      label: "Requested Change"
      description: "What should the new information be?"
      placeholder: |
        Example:
        - Add subcategory "Any% No Major Glitches" under "Any%"
        - Definition: Reach the credits without using major glitches (wall clips, OOB)
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: "Reason for Change"
      description: "Why is this change needed? Include links to community discussions if available."
      placeholder: |
        Example:
        - The community has been running NMG as a separate category for 6 months
        - Discussion thread: https://discord.com/...
        - Speedrun.com page: https://speedrun.com/...

  - type: input
    id: discord_handle
    attributes:
      label: "Discord Handle (Optional)"
      description: "Your Discord username if we need to follow up"
      placeholder: "username#1234 or @username"

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: "Acknowledgment"
      options:
        - label: "I understand that changes are subject to moderator review and may be modified or rejected"
          required: true
