name: "🦋 Hollow Knight Run Submission"
description: Submit a Hollow Knight challenge run for review
title: "[HK Run] <category> - <challenge> - <runner>"
labels: ["run-submission", "pending-review", "hollow-knight"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit Your Hollow Knight Challenge Run
        
        Fill out all required fields below. A moderator will review your submission.
        
        **Video Requirements:**
        - YouTube, Twitch Highlight/Clip, or Bilibili
        - ⚠️ Regular Twitch VODs expire! Use Highlights instead.
        - Main menu must be shown to verify no illegal mods
        
        ---

  # ============================================================
  # RUNNER INFO
  # ============================================================
  - type: input
    id: runner
    attributes:
      label: Runner Name
      description: How your name should appear on the leaderboard
      placeholder: "e.g., MyPetCactus"
    validations:
      required: true

  - type: input
    id: runner_id
    attributes:
      label: Runner ID
      description: URL-safe ID (lowercase, hyphens). This will be in your profile URL.
      placeholder: "e.g., mypetcactus"
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Discord / Contact (Optional)
      description: How to reach you if we have questions
      placeholder: "e.g., username"

  # ============================================================
  # CATEGORY SELECTION
  # ============================================================
  - type: dropdown
    id: category_slug
    attributes:
      label: Category
      description: What category is this run?
      options:
        - any
        - all-skills
        - 112-apb
        - 107-ab
        - 106-te
        - true-ending
        - low-percent
        - godhome-ending
        - all-bosses
        - pantheons/pantheon-1
        - pantheons/pantheon-2
        - pantheons/pantheon-3
        - pantheons/pantheon-4
        - pantheons/pantheon-5
        - boss-rush/all-radiant
        - boss-rush/hall-of-gods
        - OTHER (specify below)
    validations:
      required: true

  - type: input
    id: category_other
    attributes:
      label: Category (if OTHER)
      description: Only fill this if you selected "OTHER" above
      placeholder: "e.g., specific-boss-name"

  - type: input
    id: category_label
    attributes:
      label: Category Display Name
      description: How the category should appear
      placeholder: "e.g., Any%, Pantheon of Hallownest"
    validations:
      required: true

  # ============================================================
  # CHALLENGE TYPE
  # ============================================================
  - type: dropdown
    id: challenge_id
    attributes:
      label: Challenge Type
      description: What type of challenge run is this?
      options:
        - hitless
        - damageless
        - deathless
        - no-hit-no-damage
        - blindfolded
        - steel-soul
        - low-percent
        - pantheon-hitless
        - radiant-bosses
        - OTHER (specify below)
    validations:
      required: true

  - type: input
    id: challenge_other
    attributes:
      label: Challenge Type (if OTHER)
      description: Only fill this if you selected "OTHER" above
      placeholder: "e.g., one-handed"

  # ============================================================
  # GLITCH CATEGORY
  # ============================================================
  - type: dropdown
    id: glitch_category
    attributes:
      label: Glitch Category
      description: What glitch rules did you follow?
      options:
        - unrestricted
        - nmg
        - glitchless
        - no-main-menu-storage
    validations:
      required: true

  # ============================================================
  # VIDEO & TIMING
  # ============================================================
  - type: input
    id: video_link
    attributes:
      label: Video Link
      description: |
        YouTube, Twitch Highlight/Clip, or Bilibili.
        ⚠️ Regular Twitch VODs expire! Please use a Highlight.
      placeholder: "https://www.youtube.com/watch?v=..."
    validations:
      required: true

  - type: input
    id: date_completed
    attributes:
      label: Date Completed
      description: When did you complete this run? (YYYY-MM-DD)
      placeholder: "2025-01-10"
    validations:
      required: true

  - type: input
    id: time_lrt
    attributes:
      label: Time (LRT - Load Removed)
      description: "Format: HH:MM:SS or MM:SS"
      placeholder: "31:24"

  - type: input
    id: time_rta
    attributes:
      label: Time (RTA - Real Time)
      description: "Optional if you have LRT. Format: HH:MM:SS"
      placeholder: "36:40"

  # ============================================================
  # GAME VERSION
  # ============================================================
  - type: dropdown
    id: patch_version
    attributes:
      label: Game Patch Version
      description: What version of Hollow Knight?
      options:
        - 1.5.78 (Current)
        - 1.4.3.2
        - 1.2.2.1 (NMG speedrun standard)
        - Other (specify in notes)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform did you play on?
      options:
        - PC (Steam)
        - PC (GOG)
        - PlayStation
        - Xbox
        - Nintendo Switch
    validations:
      required: true

  # ============================================================
  # ADDITIONAL RESTRICTIONS
  # ============================================================
  - type: checkboxes
    id: restrictions
    attributes:
      label: Additional Restrictions (Optional)
      description: Did you apply any additional restrictions?
      options:
        - label: No Charms
        - label: No Nail Upgrades
        - label: No Spells
        - label: Base Nail Only
        - label: No Shade Cloak

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Anything else we should know? Custom restrictions, notable moments, etc.
      placeholder: |
        First completion of this category
        Timestamp of key moments: 15:23 (boss fight)

  # ============================================================
  # VERIFICATION
  # ============================================================
  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following (required by Team Hitless rules)
      options:
        - label: Main menu is shown in video (to verify no illegal mods)
          required: true
        - label: This video shows my own gameplay
          required: true
        - label: The video is publicly accessible and permanent (not a temporary VOD)
          required: true
        - label: I understand Baldur Shell / Dreamshield blocks count as hits for hitless runs
          required: true
