name: "🎮 New Game Submission"
description: "Submit a new game to be added to Challenge Run Central"
title: "[New Game] "
labels: ["new-game", "pending-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit a New Game
        
        Use this form to request a new game be added to Challenge Run Central.
        
        **Before submitting:**
        - Check that the game isn't already listed
        - Have information about categories and challenge types ready
        
        A moderator will review your submission and may follow up with questions.

  # ============================================================
  # GAME IDENTITY
  # ============================================================
  - type: input
    id: game_name
    attributes:
      label: Game Name
      description: The full, official name of the game
      placeholder: "e.g., Hollow Knight"
    validations:
      required: true

  - type: input
    id: game_id
    attributes:
      label: Game ID (URL Slug)
      description: "Lowercase with hyphens, used in URLs. Example: hollow-knight"
      placeholder: "e.g., hollow-knight"
    validations:
      required: true

  - type: input
    id: aliases
    attributes:
      label: Alternate Names / Abbreviations
      description: "Other names the game is known by (comma separated)"
      placeholder: "e.g., HK, Hollow"

  # ============================================================
  # PLATFORMS & GENRES
  # ============================================================
  - type: checkboxes
    id: platforms
    attributes:
      label: Platforms
      description: Select all platforms the game is available on
      options:
        - label: PC (Steam)
        - label: PC (Epic Games Store)
        - label: PC (GOG)
        - label: PC (Other)
        - label: PlayStation 4
        - label: PlayStation 5
        - label: Xbox One
        - label: Xbox Series X/S
        - label: Nintendo Switch
        - label: Mobile (iOS/Android)
        - label: Other (specify in notes)

  - type: input
    id: genres
    attributes:
      label: Genres / Tags
      description: "Comma-separated list of genres (e.g., action, roguelike, metroidvania)"
      placeholder: "e.g., action, roguelike, indie"
    validations:
      required: true

  # ============================================================
  # CATEGORIES
  # ============================================================
  - type: textarea
    id: categories
    attributes:
      label: Speedrun Categories
      description: |
        List the main speedrun categories for this game.
        One per line. Use format: slug - Display Name
        For subcategories, use parent/child format.
      placeholder: |
        any - Any%
        all-bosses - All Bosses
        100-percent - 100%
        ng-plus/any - NG+ Any%
        ng-plus/all-bosses - NG+ All Bosses
    validations:
      required: true

  # ============================================================
  # CHALLENGE TYPES
  # ============================================================
  - type: checkboxes
    id: standard_challenges
    attributes:
      label: Standard Challenge Types
      description: Select which standard challenge types apply to this game
      options:
        - label: Hitless (no damage taken)
        - label: Damageless (no health lost)
        - label: Deathless (no deaths)
        - label: No Hit No Damage (combined)
        - label: Blindfolded

  - type: textarea
    id: community_challenges
    attributes:
      label: Game-Specific Community Challenges
      description: |
        List any challenge types unique to this game's community.
        One per line. Use format: slug - Display Name - Description
      placeholder: |
        steel-soul - Steel Soul - Permadeath mode
        low-percent - Low% - Minimum items/upgrades
        pacifist - Pacifist - No killing enemies

  # ============================================================
  # GLITCH RULES
  # ============================================================
  - type: checkboxes
    id: glitch_categories
    attributes:
      label: Glitch Categories
      description: Which glitch rule categories does the community use?
      options:
        - label: Unrestricted (any glitches allowed)
        - label: No Major Glitches (NMG)
        - label: Glitchless
        - label: Other (specify in notes)

  - type: input
    id: glitch_docs
    attributes:
      label: Glitch Documentation Link
      description: Link to glitch rules or documentation (optional)
      placeholder: "https://..."

  # ============================================================
  # TIMING
  # ============================================================
  - type: dropdown
    id: timing_method
    attributes:
      label: Primary Timing Method
      description: How are runs typically timed?
      options:
        - RTA (Real Time Attack)
        - LRT (Load Removed Time)
        - IGT (In-Game Time)
        - Other (specify in notes)
    validations:
      required: true

  # ============================================================
  # CHARACTER/CLASS COLUMN
  # ============================================================
  - type: dropdown
    id: character_column
    attributes:
      label: Does this game need a Character/Class column?
      description: Some games track runs by character, class, weapon, etc.
      options:
        - "No"
        - "Yes - Character"
        - "Yes - Class"
        - "Yes - Weapon"
        - "Yes - Other (specify in notes)"
    validations:
      required: true

  - type: input
    id: character_options
    attributes:
      label: Character/Class Options
      description: "If yes above, list the options (comma separated)"
      placeholder: "e.g., Melinoe, Zagreus"

  # ============================================================
  # RESOURCES
  # ============================================================
  - type: textarea
    id: resources
    attributes:
      label: Community Resources
      description: Links to speedrun.com, Discord, wikis, etc.
      placeholder: |
        Speedrun.com: https://speedrun.com/gamename
        Discord: https://discord.gg/invite
        Wiki: https://...

  # ============================================================
  # ADDITIONAL INFO
  # ============================================================
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other information moderators should know

  - type: input
    id: discord_handle
    attributes:
      label: Your Discord Handle (Optional)
      description: So we can follow up if needed
      placeholder: "username"

  # ============================================================
  # CONFIRMATION
  # ============================================================
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have checked that this game is not already on the site
          required: true
        - label: I am familiar with this game's challenge run community
          required: true
        - label: I understand my submission will be reviewed and may be modified
          required: true
