name: "🎮 Run Submission"
description: Submit a challenge run for review
title: "[RUN] <game> - <category> - <runner>"
labels: ["run-submission", "pending-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit Your Challenge Run
        
        **Prefer Google Form?** [Submit via Google Form](https://forms.google.com/YOUR_FORM_ID) (same process, friendlier interface)
        
        ---
        
        Fill out all required fields below. A moderator will review your submission within 48 hours.

  # ============================================================
  # GAME SELECTION
  # ============================================================
  - type: dropdown
    id: game_id
    attributes:
      label: Game
      description: Select your game. If not listed, choose "Other" and specify below.
      options:
        - hades-2
        - OTHER (specify below)
    validations:
      required: true

  - type: input
    id: game_other
    attributes:
      label: Game (if not listed)
      description: Only fill this if you selected "OTHER" above. Use lowercase-with-hyphens format.
      placeholder: "e.g., hollow-knight"
    validations:
      required: false

  # ============================================================
  # RUNNER INFO
  # ============================================================
  - type: input
    id: runner
    attributes:
      label: Runner Name (Display)
      description: How your name should appear on the leaderboard
      placeholder: "e.g., Gary Asher"
    validations:
      required: true

  - type: input
    id: runner_id
    attributes:
      label: Runner ID
      description: URL-safe ID (lowercase, hyphens only). This will be in your profile URL.
      placeholder: "e.g., gary-asher"
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact (Optional)
      description: Discord username or other way to reach you if we have questions
      placeholder: "e.g., Discord: username#1234"
    validations:
      required: false

  # ============================================================
  # RUN DETAILS
  # ============================================================
  - type: dropdown
    id: category_slug
    attributes:
      label: Category
      description: Select the run category
      options:
        # Hades 2 categories
        - underworld-any
        - underworld-vor4
        - surface-any
        - surface-vor4
        - chaos-trials
        - chaos-trials/trial-of-blood
        - chaos-trials/trial-of-destiny
        - chaos-trials/trial-of-doom
        - chaos-trials/trial-of-flame
        - chaos-trials/trial-of-fury
        - chaos-trials/trial-of-gold
        - chaos-trials/trial-of-haste
        - chaos-trials/trial-of-heartache
        - chaos-trials/trial-of-humility
        - chaos-trials/trial-of-moon
        - chaos-trials/trial-of-origin
        - chaos-trials/trial-of-precarity
        - chaos-trials/trial-of-salt
        - chaos-trials/trial-of-vengeance
        - chaos-trials/trial-of-vigor
        - OTHER (specify below)
    validations:
      required: true

  - type: input
    id: category_other
    attributes:
      label: Category (if not listed)
      description: Only fill this if you selected "OTHER" above
      placeholder: "e.g., new-category-name"
    validations:
      required: false

  - type: input
    id: category_label
    attributes:
      label: Category Display Name
      description: How the category should appear (e.g., "Underworld Any%")
      placeholder: "e.g., Underworld Any%"
    validations:
      required: true

  - type: dropdown
    id: challenge_id
    attributes:
      label: Challenge Type
      description: What type of challenge run is this?
      options:
        - hitless
        - no-damage
        - deathless
        - no-hit-no-damage
        - OTHER (specify below)
    validations:
      required: true

  - type: input
    id: challenge_other
    attributes:
      label: Challenge Type (if not listed)
      description: Only fill this if you selected "OTHER" above
      placeholder: "e.g., pacifist"
    validations:
      required: false

  # ============================================================
  # VIDEO & TIMING
  # ============================================================
  - type: input
    id: video_link
    attributes:
      label: Video Link
      description: YouTube or Twitch VOD link (required for verification)
      placeholder: "https://www.youtube.com/watch?v=..."
    validations:
      required: true

  - type: input
    id: date_completed
    attributes:
      label: Date Completed
      description: When did you complete this run? (YYYY-MM-DD format)
      placeholder: "2025-01-04"
    validations:
      required: true

  - type: input
    id: time_primary
    attributes:
      label: Run Time (Optional)
      description: "Format: HH:MM:SS or HH:MM:SS.mmm"
      placeholder: "01:23:45"
    validations:
      required: false

  - type: dropdown
    id: timing_method_primary
    attributes:
      label: Timing Method
      description: How was the time measured?
      options:
        - ""
        - RTA
        - IGT
        - LRT
    validations:
      required: false

  # ============================================================
  # ADDITIONAL INFO
  # ============================================================
  - type: textarea
    id: restrictions
    attributes:
      label: Restrictions / Modifiers (Optional)
      description: Any additional restrictions on your run (one per line)
      placeholder: |
        No boons
        Base weapons only
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes (Optional)
      description: Anything else moderators should know about this run
    validations:
      required: false

  # ============================================================
  # CONFIRMATION
  # ============================================================
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: This video shows my own gameplay
          required: true
        - label: The video is publicly accessible (not private/unlisted)
          required: true
        - label: I understand my run will be reviewed by moderators
          required: true
