name: "🎮 Run Submission"
description: Submit a challenge run for review
title: "[RUN] <game> - <category> - <runner>"
labels: ["run-submission", "pending-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit Your Challenge Run
        
        Fill out all required fields below. A moderator will review your submission within 48 hours.
        
        ---
        
        ### 📹 Video Requirements
        
        **Accepted sources:**
        - ✅ YouTube (any public video)
        - ✅ Twitch **Highlights** or **Clips** (permanent)
        - ✅ Bilibili
        
        **NOT accepted:**
        - ❌ Regular Twitch VODs (they expire after ~60 days!)
        - ❌ Private/unlisted videos
        - ❌ Live stream links
        
        > 💡 **Tip:** If using Twitch, create a Highlight from your VOD to make it permanent.
        
        ---

  # ============================================================
  # GAME SELECTION
  # ============================================================
  - type: dropdown
    id: game_id
    attributes:
      label: Game
      description: Select your game. If not listed, choose "Other" and specify below.
      options:
        - hades-2
        - hollow-knight
        - OTHER (specify below)
    validations:
      required: true

  - type: input
    id: game_other
    attributes:
      label: Game (if not listed)
      description: Only fill this if you selected "OTHER" above. Use lowercase-with-hyphens format.
      placeholder: "e.g., celeste"
    validations:
      required: false

  # ============================================================
  # RUNNER INFO
  # ============================================================
  - type: input
    id: runner
    attributes:
      label: Runner Name (Display)
      description: How your name should appear on the leaderboard
      placeholder: "e.g., Gary Asher"
    validations:
      required: true

  - type: input
    id: runner_id
    attributes:
      label: Runner ID
      description: URL-safe ID (lowercase, hyphens only). This will be in your profile URL.
      placeholder: "e.g., gary-asher"
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact (Optional)
      description: Discord username or other way to reach you if we have questions
      placeholder: "e.g., Discord: username"
    validations:
      required: false

  # ============================================================
  # RUN DETAILS
  # ============================================================
  - type: input
    id: category_slug
    attributes:
      label: Category Slug
      description: "The URL-safe category ID (e.g., any, underworld-any, pantheons/pantheon-5)"
      placeholder: "e.g., any"
    validations:
      required: true

  - type: input
    id: category_label
    attributes:
      label: Category Display Name
      description: How the category should appear (e.g., "Any%", "Underworld Any%")
      placeholder: "e.g., Any%"
    validations:
      required: true

  - type: dropdown
    id: challenge_id
    attributes:
      label: Challenge Type
      description: What type of challenge run is this?
      options:
        - hitless
        - damageless
        - deathless
        - no-hit-no-damage
        - blindfolded
        - OTHER (specify below)
    validations:
      required: true

  - type: input
    id: challenge_other
    attributes:
      label: Challenge Type (if not listed)
      description: Only fill this if you selected "OTHER" above
      placeholder: "e.g., pacifist"
    validations:
      required: false

  # ============================================================
  # VIDEO & TIMING
  # ============================================================
  - type: input
    id: video_link
    attributes:
      label: Video Link
      description: |
        YouTube, Twitch Highlight/Clip, or Bilibili.
        ⚠️ Regular Twitch VODs expire! Please use a Highlight instead.
      placeholder: "https://www.youtube.com/watch?v=..."
    validations:
      required: true

  - type: input
    id: date_completed
    attributes:
      label: Date Completed
      description: When did you complete this run? (YYYY-MM-DD format)
      placeholder: "2025-01-10"
    validations:
      required: true

  - type: input
    id: time_primary
    attributes:
      label: Run Time
      description: "Format: HH:MM:SS or MM:SS.mmm"
      placeholder: "01:23:45"
    validations:
      required: false

  - type: dropdown
    id: timing_method_primary
    attributes:
      label: Timing Method
      description: How was the time measured?
      options:
        - ""
        - RTA (Real Time Attack)
        - LRT (Load Removed Time)
        - IGT (In-Game Time)
    validations:
      required: false

  # ============================================================
  # ADDITIONAL INFO
  # ============================================================
  - type: dropdown
    id: glitch_category
    attributes:
      label: Glitch Category
      description: What glitch rules did you follow?
      options:
        - ""
        - unrestricted
        - nmg
        - glitchless
    validations:
      required: false

  - type: textarea
    id: restrictions
    attributes:
      label: Restrictions / Modifiers (Optional)
      description: Any additional restrictions on your run (one per line)
      placeholder: |
        No upgrades
        Base weapons only
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes (Optional)
      description: Anything else moderators should know about this run
    validations:
      required: false

  # ============================================================
  # CONFIRMATION
  # ============================================================
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: This video shows my own gameplay
          required: true
        - label: The video is publicly accessible and will remain available (not a temporary VOD)
          required: true
        - label: I understand my run will be reviewed by moderators
          required: true
