name: Discord notification for new runs

on:
  pull_request:
    types: [opened, closed]
    paths:
      - "_queue_runs/**/*.md"
      - "_runs/**/*.md"

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse run info
        id: parse
        run: |
          # Get changed files
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          
          # Find run files
          RUN_FILE=$(echo "$FILES" | grep -E "^_runs/.+\.md$" | head -1)
          
          if [[ -z "$RUN_FILE" ]]; then
            echo "No run files found"
            echo "should_notify=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Extract info from filename
          # Format: YYYY-MM-DD__game-id__runner-id__category-slug__NN.md
          BASENAME=$(basename "$RUN_FILE" .md)
          
          GAME_ID=$(echo "$BASENAME" | cut -d'__' -f2)
          RUNNER_ID=$(echo "$BASENAME" | cut -d'__' -f3)
          CATEGORY=$(echo "$BASENAME" | cut -d'__' -f4)
          
          echo "should_notify=true" >> $GITHUB_OUTPUT
          echo "game_id=$GAME_ID" >> $GITHUB_OUTPUT
          echo "runner_id=$RUNNER_ID" >> $GITHUB_OUTPUT
          echo "category=$CATEGORY" >> $GITHUB_OUTPUT
          echo "run_file=$RUN_FILE" >> $GITHUB_OUTPUT

      - name: Send Discord notification
        if: steps.parse.outputs.should_notify == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          GAME_ID="${{ steps.parse.outputs.game_id }}"
          RUNNER_ID="${{ steps.parse.outputs.runner_id }}"
          CATEGORY="${{ steps.parse.outputs.category }}"
          
          # Format runner name
          RUNNER_NAME=$(echo "$RUNNER_ID" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
          
          # Format category name
          CATEGORY_NAME=$(echo "$CATEGORY" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
          
          # Build Discord embed
          cat << EOF > discord_payload.json
          {
            "embeds": [{
              "title": "🎮 New Challenge Run Verified!",
              "color": 3901635,
              "fields": [
                {
                  "name": "Runner",
                  "value": "$RUNNER_NAME",
                  "inline": true
                },
                {
                  "name": "Game",
                  "value": "$GAME_ID",
                  "inline": true
                },
                {
                  "name": "Category",
                  "value": "$CATEGORY_NAME",
                  "inline": true
                }
              ],
              "footer": {
                "text": "Challenge Run Community"
              },
              "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            }]
          }
          EOF
          
          curl -H "Content-Type: application/json" \
               -d @discord_payload.json \
               "$DISCORD_WEBHOOK"
